apiVersion: v1
kind: Service
metadata:
  name: hello-kube-service

spec:
  type: LoadBalancer
  selector:
    app: hello-kube

  ports:
    - name: hello
      port: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-kube-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hello-kube

  template:
    metadata:
      labels:
        app: hello-kube

    spec:
      containers:
        - name: hello
          image: eu.gcr.io/microservices-193312/hello-kube
          ports:
            - containerPort: 8080
